# This workflow will prebuild native binaries for supported NodeJS versions,
# and add them to the Github release that triggered the workflow

name: Add native binaries to release

on:
  release:
    types: [created]

jobs:
  augment-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: patch node gyp on windows to support Visual Studio 2019
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          npm install --global node-gyp@7.1.2
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
      - name: build using node-pre-gyp
        run: |
          npm install --build-from-source
          ./node_modules/.bin/node-pre-gyp package
      - name: Upload native binaries for Node ${{ matrix.node-version }} for ${{ matrix.os }}
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./node_modules/.bin/node-pre-gyp-github publish
